-- vim.api.nvim_create_autocmd('BufEnter', {
--   pattern = {
--     "*.lua",
--     "*.js",
--     "*.ts",
--   },
--   callback = function ()
--     vim.opt_local.ts = 2
--     vim.opt_local.sw = 2
--   end
-- })
